#' Add Continent Column to Press Freedom Data
#'
#' Adds a character column `Continent` to a data frame containing press freedom data,
#' indicating the continent of each country.
#'
#' The function uses the `iso` (ISO 3166-1 alpha-3) column to map countries to their
#' respective continents: Africa, Americas, Asia, Europe, or Oceania.
#'
#' @param data A data frame containing at least the column `iso` (character,
#'   ISO 3166-1 alpha-3 country code). Designed for use with
#'   `pressfreedom.data::rbw_standardized`.
#'
#' @return The input data frame with an additional character column `Continent`:
#'   the name of the continent for each country.
#'
#' @examples
#' library(pressfreedom.data)
#' rbw_standardized |> add_continent_column()
#'
add_continent_column <- function(data) {
  # Mapping of ISO codes to continents
  continent_mapping <- tibble::tribble(
    ~iso,   ~Continent,
    # Africa
    "DZA",  "Africa",
    "AGO",  "Africa",
    "BEN",  "Africa",
    "BWA",  "Africa",
    "BFA",  "Africa",
    "BDI",  "Africa",
    "CMR",  "Africa",
    "CPV",  "Africa",
    "CAF",  "Africa",
    "TCD",  "Africa",
    "COM",  "Africa",
    "COG",  "Africa",
    "COD",  "Africa",
    "CIV",  "Africa",
    "DJI",  "Africa",
    "EGY",  "Africa",
    "GNQ",  "Africa",
    "ERI",  "Africa",
    "ETH",  "Africa",
    "GAB",  "Africa",
    "GMB",  "Africa",
    "GHA",  "Africa",
    "GIN",  "Africa",
    "GNB",  "Africa",
    "KEN",  "Africa",
    "LSO",  "Africa",
    "LBR",  "Africa",
    "LBY",  "Africa",
    "MDG",  "Africa",
    "MWI",  "Africa",
    "MLI",  "Africa",
    "MRT",  "Africa",
    "MUS",  "Africa",
    "MAR",  "Africa",
    "MOZ",  "Africa",
    "NAM",  "Africa",
    "NER",  "Africa",
    "NGA",  "Africa",
    "RWA",  "Africa",
    "STP",  "Africa",
    "SEN",  "Africa",
    "SYC",  "Africa",
    "SLE",  "Africa",
    "SOM",  "Africa",
    "ZAF",  "Africa",
    "SSD",  "Africa",
    "SDN",  "Africa",
    "SWZ",  "Africa",
    "TZA",  "Africa",
    "TGO",  "Africa",
    "TUN",  "Africa",
    "UGA",  "Africa",
    "ZMB",  "Africa",
    "ZWE",  "Africa",
    # Americas
    "ATG",  "Americas",
    "ARG",  "Americas",
    "BHS",  "Americas",
    "BRB",  "Americas",
    "BLZ",  "Americas",
    "BOL",  "Americas",
    "BRA",  "Americas",
    "CAN",  "Americas",
    "CHL",  "Americas",
    "COL",  "Americas",
    "CRI",  "Americas",
    "CUB",  "Americas",
    "DMA",  "Americas",
    "DOM",  "Americas",
    "ECU",  "Americas",
    "SLV",  "Americas",
    "GRD",  "Americas",
    "GTM",  "Americas",
    "GUY",  "Americas",
    "HTI",  "Americas",
    "HND",  "Americas",
    "JAM",  "Americas",
    "MEX",  "Americas",
    "NIC",  "Americas",
    "PAN",  "Americas",
    "PRY",  "Americas",
    "PER",  "Americas",
    "KNA",  "Americas",
    "LCA",  "Americas",
    "VCT",  "Americas",
    "SUR",  "Americas",
    "TTO",  "Americas",
    "USA",  "Americas",
    "URY",  "Americas",
    "VEN",  "Americas",
    # Asia
    "AFG",  "Asia",
    "ARM",  "Asia",
    "AZE",  "Asia",
    "BHR",  "Asia",
    "BGD",  "Asia",
    "BTN",  "Asia",
    "BRN",  "Asia",
    "KHM",  "Asia",
    "CHN",  "Asia",
    "GEO",  "Asia",
    "HKG",  "Asia",
    "IND",  "Asia",
    "IDN",  "Asia",
    "IRN",  "Asia",
    "IRQ",  "Asia",
    "ISR",  "Asia",
    "JPN",  "Asia",
    "JOR",  "Asia",
    "KAZ",  "Asia",
    "KWT",  "Asia",
    "KGZ",  "Asia",
    "LAO",  "Asia",
    "LBN",  "Asia",
    "MAC",  "Asia",
    "MYS",  "Asia",
    "MDV",  "Asia",
    "MNG",  "Asia",
    "MMR",  "Asia",
    "NPL",  "Asia",
    "PRK",  "Asia",
    "OMN",  "Asia",
    "PAK",  "Asia",
    "PSE",  "Asia",
    "PHL",  "Asia",
    "QAT",  "Asia",
    "SAU",  "Asia",
    "SGP",  "Asia",
    "KOR",  "Asia",
    "LKA",  "Asia",
    "SYR",  "Asia",
    "TWN",  "Asia",
    "TJK",  "Asia",
    "THA",  "Asia",
    "TLS",  "Asia",
    "TUR",  "Asia",
    "TKM",  "Asia",
    "ARE",  "Asia",
    "UZB",  "Asia",
    "VNM",  "Asia",
    "YEM",  "Asia",
    # Europe
    "AUT",  "Europe",
    "BLR",  "Europe",
    "BEL",  "Europe",
    "BIH",  "Europe",
    "BGR",  "Europe",
    "HRV",  "Europe",
    "CYP",  "Europe",
    "CZE",  "Europe",
    "DNK",  "Europe",
    "EST",  "Europe",
    "FIN",  "Europe",
    "FRA",  "Europe",
    "DEU",  "Europe",
    "GRC",  "Europe",
    "HUN",  "Europe",
    "ISL",  "Europe",
    "IRL",  "Europe",
    "ITA",  "Europe",
    "XKX",  "Europe",
    "LVA",  "Europe",
    "LIE",  "Europe",
    "LTU",  "Europe",
    "LUX",  "Europe",
    "MKD",  "Europe",
    "MLT",  "Europe",
    "MDA",  "Europe",
    "MCO",  "Europe",
    "MNE",  "Europe",
    "NLD",  "Europe",
    "NOR",  "Europe",
    "POL",  "Europe",
    "PRT",  "Europe",
    "ROU",  "Europe",
    "RUS",  "Europe",
    "SMR",  "Europe",
    "SRB",  "Europe",
    "SVK",  "Europe",
    "SVN",  "Europe",
    "ESP",  "Europe",
    "SWE",  "Europe",
    "CHE",  "Europe",
    "UKR",  "Europe",
    "GBR",  "Europe",
    "ALB",  "Europe",
    "AND",  "Europe",
    "SCG",  "Europe",
    "YUG",  "Europe",
    "XXK",  "Europe",
    # Oceania
    "AUS",  "Oceania",
    "FJI",  "Oceania",
    "KIR",  "Oceania",
    "MHL",  "Oceania",
    "FSM",  "Oceania",
    "NRU",  "Oceania",
    "NZL",  "Oceania",
    "PLW",  "Oceania",
    "PNG",  "Oceania",
    "WSM",  "Oceania",
    "SLB",  "Oceania",
    "TON",  "Oceania",
    "TUV",  "Oceania",
    "VUT",  "Oceania"
  )

  data |>
    dplyr::left_join(continent_mapping, by = "iso")
}
